In [1]:
# importing libraries
import pandas as pd
import numpy as np
pd.set_option('max_colwidth', 400)
from pytz import timezone
from datetime import datetime
import hvplot.pandas
from pathlib import Path
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [2]:
# load Heart data csv
Heart_2022 = pd.read_csv('Resources\heart_2022_no_nans.csv')
Heart_2022.head(-20)

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ago),Yes,9.0,None of them,No,...,1.60,71.67,27.99,No,No,Yes,Yes,"Yes, received Tdap",No,No
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ago),Yes,6.0,None of them,No,...,1.78,95.25,30.13,No,No,Yes,Yes,"Yes, received tetanus shot but not sure what type",No,No
2,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ago),No,8.0,"6 or more, but not all",No,...,1.85,108.86,31.66,Yes,No,No,Yes,"No, did not receive any tetanus shot in the past 10 years",No,Yes
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ago),Yes,9.0,None of them,No,...,1.70,90.72,31.32,No,No,Yes,Yes,"No, did not receive any tetanus shot in the past 10 years",No,Yes
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ago),Yes,5.0,1 to 5,No,...,1.55,79.38,33.07,No,No,Yes,Yes,"No, did not receive any tetanus shot in the past 10 years",No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245997,Virgin Islands,Female,Good,4.0,3.0,Within past 2 years (1 year but less than 2 years ago),Yes,5.0,None of them,No,...,1.68,108.86,38.74,Yes,Yes,No,Yes,"Yes, received tetanus shot but not sure what type",No,Yes
245998,Virgin Islands,Female,Good,2.0,10.0,Within past 2 years (1 year but less than 2 years ago),Yes,7.0,"6 or more, but not all",No,...,1.73,142.88,47.90,Yes,Yes,No,No,"Yes, received tetanus shot but not sure what type",No,No
245999,Virgin Islands,Female,Fair,0.0,3.0,Within past 5 years (2 years but less than 5 years ago),Yes,5.0,"6 or more, but not all",No,...,1.57,108.86,43.90,No,No,No,No,"No, did not receive any tetanus shot in the past 10 years",No,No
246000,Virgin Islands,Female,Excellent,0.0,30.0,Within past year (anytime less than 12 months ago),Yes,5.0,1 to 5,No,...,1.78,77.11,24.39,Yes,Yes,No,No,"No, did not receive any tetanus shot in the past 10 years",No,No
246001,Virgin Islands,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ago),Yes,7.0,None of them,No,...,1.85,112.94,32.85,Yes,Yes,No,No,"No, did not receive any tetanus shot in the past 10 years",No,No

In [3]:
# Dropping BMI
Heart_2022.drop(columns=['BMI'], inplace=True)
Heart_2022.head(-20)

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,AgeCategory,HeightInMeters,WeightInKilograms,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ago),Yes,9.0,None of them,No,...,Age 65 to 69,1.60,71.67,No,No,Yes,Yes,"Yes, received Tdap",No,No
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ago),Yes,6.0,None of them,No,...,Age 70 to 74,1.78,95.25,No,No,Yes,Yes,"Yes, received tetanus shot but not sure what type",No,No
2,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ago),No,8.0,"6 or more, but not all",No,...,Age 75 to 79,1.85,108.86,Yes,No,No,Yes,"No, did not receive any tetanus shot in the past 10 years",No,Yes
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ago),Yes,9.0,None of them,No,...,Age 80 or older,1.70,90.72,No,No,Yes,Yes,"No, did not receive any tetanus shot in the past 10 years",No,Yes
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ago),Yes,5.0,1 to 5,No,...,Age 80 or older,1.55,79.38,No,No,Yes,Yes,"No, did not receive any tetanus shot in the past 10 years",No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245997,Virgin Islands,Female,Good,4.0,3.0,Within past 2 years (1 year but less than 2 years ago),Yes,5.0,None of them,No,...,Age 35 to 39,1.68,108.86,Yes,Yes,No,Yes,"Yes, received tetanus shot but not sure what type",No,Yes
245998,Virgin Islands,Female,Good,2.0,10.0,Within past 2 years (1 year but less than 2 years ago),Yes,7.0,"6 or more, but not all",No,...,Age 35 to 39,1.73,142.88,Yes,Yes,No,No,"Yes, received tetanus shot but not sure what type",No,No
245999,Virgin Islands,Female,Fair,0.0,3.0,Within past 5 years (2 years but less than 5 years ago),Yes,5.0,"6 or more, but not all",No,...,Age 50 to 54,1.57,108.86,No,No,No,No,"No, did not receive any tetanus shot in the past 10 years",No,No
246000,Virgin Islands,Female,Excellent,0.0,30.0,Within past year (anytime less than 12 months ago),Yes,5.0,1 to 5,No,...,Age 50 to 54,1.78,77.11,Yes,Yes,No,No,"No, did not receive any tetanus shot in the past 10 years",No,No
246001,Virgin Islands,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ago),Yes,7.0,None of them,No,...,Age 55 to 59,1.85,112.94,Yes,Yes,No,No,"No, did not receive any tetanus shot in the past 10 years",No,No

In [4]:
columns_to_replace = ['PhysicalActivities', 'HadHeartAttack', 'HadAngina','HadStroke','HadAsthma','HadSkinCancer','HadCOPD','HadDepressiveDisorder','HadKidneyDisease','HadArthritis','HadDiabetes','DeafOrHardOfHearing','BlindOrVisionDifficulty','DifficultyConcentrating','DifficultyWalking','DifficultyDressingBathing','DifficultyErrands','ChestScan','AlcoholDrinkers','HIVTesting','FluVaxLast12', 'PneumoVaxEver', 'HighRiskLastYear','CovidPos']
replacement_dict = {'Yes': 1, 'No': 0}
#Replace all the yes/no columns
for col in columns_to_replace:
    Heart_2022[col] = Heart_2022[col].replace(replacement_dict)
Heart_2022.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,AgeCategory,HeightInMeters,WeightInKilograms,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ago),1,9.0,None of them,0,...,Age 65 to 69,1.60,71.67,0,0,1,1,"Yes, received Tdap",0,0
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ago),1,6.0,None of them,0,...,Age 70 to 74,1.78,95.25,0,0,1,1,"Yes, received tetanus shot but not sure what type",0,0
2,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ago),0,8.0,"6 or more, but not all",0,...,Age 75 to 79,1.85,108.86,1,0,0,1,"No, did not receive any tetanus shot in the past 10 years",0,1
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ago),1,9.0,None of them,0,...,Age 80 or older,1.70,90.72,0,0,1,1,"No, did not receive any tetanus shot in the past 10 years",0,1
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ago),1,5.0,1 to 5,0,...,Age 80 or older,1.55,79.38,0,0,1,1,"No, did not receive any tetanus shot in the past 10 years",0,0

In [5]:
replacement_dict = {'Male': 0, 'Female': 1}
Heart_2022['Sex'] = Heart_2022['Sex'].replace(replacement_dict)
#Replacing the sex column
Heart_2022.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,AgeCategory,HeightInMeters,WeightInKilograms,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,1,Very good,4.0,0.0,Within past year (anytime less than 12 months ago),1,9.0,None of them,0,...,Age 65 to 69,1.60,71.67,0,0,1,1,"Yes, received Tdap",0,0
1,Alabama,0,Very good,0.0,0.0,Within past year (anytime less than 12 months ago),1,6.0,None of them,0,...,Age 70 to 74,1.78,95.25,0,0,1,1,"Yes, received tetanus shot but not sure what type",0,0
2,Alabama,0,Very good,0.0,0.0,Within past year (anytime less than 12 months ago),0,8.0,"6 or more, but not all",0,...,Age 75 to 79,1.85,108.86,1,0,0,1,"No, did not receive any tetanus shot in the past 10 years",0,1
3,Alabama,1,Fair,5.0,0.0,Within past year (anytime less than 12 months ago),1,9.0,None of them,0,...,Age 80 or older,1.70,90.72,0,0,1,1,"No, did not receive any tetanus shot in the past 10 years",0,1
4,Alabama,1,Good,3.0,15.0,Within past year (anytime less than 12 months ago),1,5.0,1 to 5,0,...,Age 80 or older,1.55,79.38,0,0,1,1,"No, did not receive any tetanus shot in the past 10 years",0,0

In [6]:
replacement_dict = {'Poor': 0, 'Fair': 1, 'Good':2,'Very good':3,'Excellent':4}
Heart_2022['GeneralHealth'] = Heart_2022['GeneralHealth'].replace(replacement_dict)
#Replacing General Health column
Heart_2022.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,AgeCategory,HeightInMeters,WeightInKilograms,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,1,3,4.0,0.0,Within past year (anytime less than 12 months ago),1,9.0,None of them,0,...,Age 65 to 69,1.60,71.67,0,0,1,1,"Yes, received Tdap",0,0
1,Alabama,0,3,0.0,0.0,Within past year (anytime less than 12 months ago),1,6.0,None of them,0,...,Age 70 to 74,1.78,95.25,0,0,1,1,"Yes, received tetanus shot but not sure what type",0,0
2,Alabama,0,3,0.0,0.0,Within past year (anytime less than 12 months ago),0,8.0,"6 or more, but not all",0,...,Age 75 to 79,1.85,108.86,1,0,0,1,"No, did not receive any tetanus shot in the past 10 years",0,1
3,Alabama,1,1,5.0,0.0,Within past year (anytime less than 12 months ago),1,9.0,None of them,0,...,Age 80 or older,1.70,90.72,0,0,1,1,"No, did not receive any tetanus shot in the past 10 years",0,1
4,Alabama,1,2,3.0,15.0,Within past year (anytime less than 12 months ago),1,5.0,1 to 5,0,...,Age 80 or older,1.55,79.38,0,0,1,1,"No, did not receive any tetanus shot in the past 10 years",0,0

In [7]:
#build a dictionary of values to replace using unique values in column
replacement = {}
replacement = Heart_2022['State'].unique()
replacement_dict = {}
n=len(replacement)
for i in range(n):
    replacement_dict[replacement[i]]=i

Heart_2022['State'] = Heart_2022['State'].replace(replacement_dict)
Heart_2022.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,AgeCategory,HeightInMeters,WeightInKilograms,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,0,1,3,4.0,0.0,Within past year (anytime less than 12 months ago),1,9.0,None of them,0,...,Age 65 to 69,1.60,71.67,0,0,1,1,"Yes, received Tdap",0,0
1,0,0,3,0.0,0.0,Within past year (anytime less than 12 months ago),1,6.0,None of them,0,...,Age 70 to 74,1.78,95.25,0,0,1,1,"Yes, received tetanus shot but not sure what type",0,0
2,0,0,3,0.0,0.0,Within past year (anytime less than 12 months ago),0,8.0,"6 or more, but not all",0,...,Age 75 to 79,1.85,108.86,1,0,0,1,"No, did not receive any tetanus shot in the past 10 years",0,1
3,0,1,1,5.0,0.0,Within past year (anytime less than 12 months ago),1,9.0,None of them,0,...,Age 80 or older,1.70,90.72,0,0,1,1,"No, did not receive any tetanus shot in the past 10 years",0,1
4,0,1,2,3.0,15.0,Within past year (anytime less than 12 months ago),1,5.0,1 to 5,0,...,Age 80 or older,1.55,79.38,0,0,1,1,"No, did not receive any tetanus shot in the past 10 years",0,0

In [8]:
#build a dictionary of values to replace using unique values in column
replacement = {}
replacement = Heart_2022['LastCheckupTime'].unique()
replacement_dict = {}
n=len(replacement)
for i in range(n):
    replacement_dict[replacement[i]]=i

#Replacing column
Heart_2022['LastCheckupTime'] = Heart_2022['LastCheckupTime'].replace(replacement_dict)
Heart_2022.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,AgeCategory,HeightInMeters,WeightInKilograms,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,0,1,3,4.0,0.0,0,1,9.0,None of them,0,...,Age 65 to 69,1.60,71.67,0,0,1,1,"Yes, received Tdap",0,0
1,0,0,3,0.0,0.0,0,1,6.0,None of them,0,...,Age 70 to 74,1.78,95.25,0,0,1,1,"Yes, received tetanus shot but not sure what type",0,0
2,0,0,3,0.0,0.0,0,0,8.0,"6 or more, but not all",0,...,Age 75 to 79,1.85,108.86,1,0,0,1,"No, did not receive any tetanus shot in the past 10 years",0,1
3,0,1,1,5.0,0.0,0,1,9.0,None of them,0,...,Age 80 or older,1.70,90.72,0,0,1,1,"No, did not receive any tetanus shot in the past 10 years",0,1
4,0,1,2,3.0,15.0,0,1,5.0,1 to 5,0,...,Age 80 or older,1.55,79.38,0,0,1,1,"No, did not receive any tetanus shot in the past 10 years",0,0

In [9]:
#build a dictionary of values to replace using unique values in column
replacement = {}
replacement = Heart_2022['RemovedTeeth'].unique()
replacement_dict = {}
n=len(replacement)
for i in range(n):
    replacement_dict[replacement[i]]=i

#Replacing column
Heart_2022['RemovedTeeth'] = Heart_2022['RemovedTeeth'].replace(replacement_dict)
Heart_2022.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,AgeCategory,HeightInMeters,WeightInKilograms,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,0,1,3,4.0,0.0,0,1,9.0,0,0,...,Age 65 to 69,1.60,71.67,0,0,1,1,"Yes, received Tdap",0,0
1,0,0,3,0.0,0.0,0,1,6.0,0,0,...,Age 70 to 74,1.78,95.25,0,0,1,1,"Yes, received tetanus shot but not sure what type",0,0
2,0,0,3,0.0,0.0,0,0,8.0,1,0,...,Age 75 to 79,1.85,108.86,1,0,0,1,"No, did not receive any tetanus shot in the past 10 years",0,1
3,0,1,1,5.0,0.0,0,1,9.0,0,0,...,Age 80 or older,1.70,90.72,0,0,1,1,"No, did not receive any tetanus shot in the past 10 years",0,1
4,0,1,2,3.0,15.0,0,1,5.0,2,0,...,Age 80 or older,1.55,79.38,0,0,1,1,"No, did not receive any tetanus shot in the past 10 years",0,0

In [10]:
#build a dictionary of values to replace using unique values in column
replacement = {}
replacement = Heart_2022['SmokerStatus'].unique()
replacement_dict = {}
n=len(replacement)
for i in range(n):
    replacement_dict[replacement[i]]=i
    
#Replacing column
Heart_2022['SmokerStatus'] = Heart_2022['SmokerStatus'].replace(replacement_dict)
Heart_2022.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,AgeCategory,HeightInMeters,WeightInKilograms,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,0,1,3,4.0,0.0,0,1,9.0,0,0,...,Age 65 to 69,1.60,71.67,0,0,1,1,"Yes, received Tdap",0,0
1,0,0,3,0.0,0.0,0,1,6.0,0,0,...,Age 70 to 74,1.78,95.25,0,0,1,1,"Yes, received tetanus shot but not sure what type",0,0
2,0,0,3,0.0,0.0,0,0,8.0,1,0,...,Age 75 to 79,1.85,108.86,1,0,0,1,"No, did not receive any tetanus shot in the past 10 years",0,1
3,0,1,1,5.0,0.0,0,1,9.0,0,0,...,Age 80 or older,1.70,90.72,0,0,1,1,"No, did not receive any tetanus shot in the past 10 years",0,1
4,0,1,2,3.0,15.0,0,1,5.0,2,0,...,Age 80 or older,1.55,79.38,0,0,1,1,"No, did not receive any tetanus shot in the past 10 years",0,0

In [11]:
#build a dictionary of values to replace using unique values in column
replacement = {}
replacement = Heart_2022['RaceEthnicityCategory'].unique()
replacement_dict = {}
n=len(replacement)
for i in range(n):
    replacement_dict[replacement[i]]=i
    
#Replacing column
Heart_2022['RaceEthnicityCategory'] = Heart_2022['RaceEthnicityCategory'].replace(replacement_dict)
Heart_2022.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,AgeCategory,HeightInMeters,WeightInKilograms,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,0,1,3,4.0,0.0,0,1,9.0,0,0,...,Age 65 to 69,1.60,71.67,0,0,1,1,"Yes, received Tdap",0,0
1,0,0,3,0.0,0.0,0,1,6.0,0,0,...,Age 70 to 74,1.78,95.25,0,0,1,1,"Yes, received tetanus shot but not sure what type",0,0
2,0,0,3,0.0,0.0,0,0,8.0,1,0,...,Age 75 to 79,1.85,108.86,1,0,0,1,"No, did not receive any tetanus shot in the past 10 years",0,1
3,0,1,1,5.0,0.0,0,1,9.0,0,0,...,Age 80 or older,1.70,90.72,0,0,1,1,"No, did not receive any tetanus shot in the past 10 years",0,1
4,0,1,2,3.0,15.0,0,1,5.0,2,0,...,Age 80 or older,1.55,79.38,0,0,1,1,"No, did not receive any tetanus shot in the past 10 years",0,0

In [12]:
#build a dictionary of values to replace using unique values in column
replacement = {}
replacement = Heart_2022['AgeCategory'].unique()
replacement_dict = {}
n=len(replacement)
for i in range(n):
    replacement_dict[replacement[i]]=i
    
#Replacing column
Heart_2022['AgeCategory'] = Heart_2022['AgeCategory'].replace(replacement_dict)
Heart_2022.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,AgeCategory,HeightInMeters,WeightInKilograms,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,0,1,3,4.0,0.0,0,1,9.0,0,0,...,0,1.60,71.67,0,0,1,1,"Yes, received Tdap",0,0
1,0,0,3,0.0,0.0,0,1,6.0,0,0,...,1,1.78,95.25,0,0,1,1,"Yes, received tetanus shot but not sure what type",0,0
2,0,0,3,0.0,0.0,0,0,8.0,1,0,...,2,1.85,108.86,1,0,0,1,"No, did not receive any tetanus shot in the past 10 years",0,1
3,0,1,1,5.0,0.0,0,1,9.0,0,0,...,3,1.70,90.72,0,0,1,1,"No, did not receive any tetanus shot in the past 10 years",0,1
4,0,1,2,3.0,15.0,0,1,5.0,2,0,...,3,1.55,79.38,0,0,1,1,"No, did not receive any tetanus shot in the past 10 years",0,0

In [13]:
#build a dictionary of values to replace using unique values in column
replacement = {}
replacement = Heart_2022['TetanusLast10Tdap'].unique()
replacement_dict = {}
n=len(replacement)
for i in range(n):
    replacement_dict[replacement[i]]=i
    
#Replacing column
Heart_2022['TetanusLast10Tdap'] = Heart_2022['TetanusLast10Tdap'].replace(replacement_dict)
Heart_2022.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,AgeCategory,HeightInMeters,WeightInKilograms,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,0,1,3,4.0,0.0,0,1,9.0,0,0,...,0,1.60,71.67,0,0,1,1,0,0,0
1,0,0,3,0.0,0.0,0,1,6.0,0,0,...,1,1.78,95.25,0,0,1,1,1,0,0
2,0,0,3,0.0,0.0,0,0,8.0,1,0,...,2,1.85,108.86,1,0,0,1,2,0,1
3,0,1,1,5.0,0.0,0,1,9.0,0,0,...,3,1.70,90.72,0,0,1,1,2,0,1
4,0,1,2,3.0,15.0,0,1,5.0,2,0,...,3,1.55,79.38,0,0,1,1,2,0,0